### PR TITLE
TO - DO Completed

### PR DESCRIPTION
**Pull request by Spr-Luis**

### CODE REVIEW

**Comment by Spr-Luis** [comment]
The plist is added, add a method to return the amount corresponding to the user's position UIImage.

**Comment by basdvries** [comment]
Thanks for your pull request! Could you extend the documentation of the readme to include your method of adding a country image?

**Comment by Spr-Luis** [comment]
Is already at the last commit. "Update Readme.md".

**Comment by basdvries** [comment]
You're right! Sorry for that. Happy new year.

**Comment by Spr-Luis** [comment]
Happy New Year! Thanks for my first Pull Request merged! (^^)

**Pull request merged**
